package io.github.vcvitaly.k8cp.enumeration;

public enum PathRefreshEventSource {
    LOCAL_INIT,
    LOCAL_TABLE_SELECTION,
    LOCAL_PARENT_BUTTON,
    LOCAL_HOME_BUTTON,
    LOCAL_ROOT_BUTTON,
    LOCAL_REFRESH_BUTTON,
    LOCAL_BREADCRUMB_SELECTION,
    LOCAL_ROOT_SELECTION,
    REMOTE_INIT,
    REMOTE_TABLE_SELECTION,
    REMOTE_PARENT_BUTTON,
    REMOTE_HOME_BUTTON,
    REMOTE_ROOT_BUTTON,
    REMOTE_REFRESH_BUTTON,
    REMOTE_BREADCRUMB_SELECTION;
}
